### ISSUE TITLE
Feature request: Option to not display start/stop messages in-game

### ISSUE THREAD

**Issue by SlimeDog** [PyroTempus/My-Plugins#24]
Spigot 1.13.1
PWP 2.0.6

I would like the option to not display start/stop messages in-game (but still at the console/log). Some possibilities:
- Do not display messages (including prefix) if they are empty strings:
```
Acidrain:
  Started: ''
  Stopped: ''
```
- Configuration option to disable them

In addition, if start/stop messages are not empty, they should be displayed (or there should be an option to display them) only to players in worlds where acid rain is enabled, or only to players in the world where the start/stop occurred.

**Comment by PyroTempus** [comment]
Added to the upcoming v2.1.0 update.
