### ISSUE TITLE
Feature request: Villagers indoors during acid rain

### ISSUE THREAD

**Issue by SlimeDog** [PyroTempus/My-Plugins#25]
I don't know if it's even possible, but it would be a great option to force villagers indoors when acid rain is falling. One possible approach: augmenting the AI so that they believe it is night, when it's raining.

Configurable option, of course.

**Comment by MostWantedMinx** [comment]
Not entirely sure if this is possible but it's something I can look into for sure.

**Comment by SlimeDog** [comment]
Thanks.

**Comment by SlimeDog** [comment]
In MC 1.14:
> Villagers will run inside at night or during rain
