### ISSUE TITLE
Feature request: Disable acid rain in creative and spectator modes

### ISSUE THREAD

**Issue by SlimeDog** [PyroTempus/My-Plugins#33]
Spigot 1.13.2 latest
PyroWeatherPro 2.1.2

Acid rain is disabled in creative mode (although I don't see a setting in config.yml). It should probably be an explicit configuration option.

Acid rain is enabled in spectator mode. It should be disabled optionally in spectator mode.

**Comment by PyroTempus** [comment]
Will add this into the next version for PWP in the coming week or so. 

Currently working on everything at the same time which breaks it up for me.
